<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-03-11 03:34

from django.db import migrations, models
=======
# Generated by Django 3.1.4 on 2026-03-12 14:27

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 507d7d53ae00c78e08bb362c85ad854ae7affc73


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('doctor', '0001_initial'),
>>>>>>> 507d7d53ae00c78e08bb362c85ad854ae7affc73
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('midname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField()),
=======
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('midname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('consultation_date', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
>>>>>>> 507d7d53ae00c78e08bb362c85ad854ae7affc73
            ],
        ),
    ]
