# Generated by Django 6.0.3 on 2026-03-12 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consultation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
