# Generated by Django 6.0.3 on 2026-03-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_consultation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='consultation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
