# Generated by Django 6.0.3 on 2026-03-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_address_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='consultation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
