# Generated by Django 6.0.3 on 2026-03-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('midname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
